# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OctoGrom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OctoGrom
  pod 'RNMobileCenter', '~> 0.1.0'
  pod 'MobileCenter', '~> 0.3.0'

  

  target 'OctoGromTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'OctoGrom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OctoGrom-tvOS

  target 'OctoGrom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
